name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * *'
    - cron: '0 21 * * *'

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Instalação de Dependências (API)
      run: npm install
      working-directory: ./API

    - name: Executar Testes de API
      run: npm run cypress:run
      working-directory: ./API

    - name: Upload Mochawesome Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mochawesome-report-api
        path: API/cypress/reports

    - name: Download Mochawesome Report
      uses: actions/download-artifact@v4
      with:
        name: mochawesome-report-api
        path: download-mochawesome-report

  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configuração do Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' 

    - name: Instalação de Dependências (UI)
      run: npm install
      working-directory: ./WEB

    - name: Executar Testes de UI
      run: npm run cy:ui-regression
      working-directory: ./WEB

    - name: Upload Mochawesome Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mochawesome-report-web
        path: WEB/cypress/reports

    - name: Download Mochawesome Report
      uses: actions/download-artifact@v4
      with:
        name: mochawesome-report-web
        path: download-mochawesome-report